#Плагин разработал TheRega.
#Если Вы обнаружите какой-либо баг, незамедлительно сообщите нам.
#Vk: vk.com/therega, группа: vk.com/waterstudio_ru


#Название мира в котором искать регионы
world: "world"

#Шанс того что пшеница вырастит от 0 до 100
grow-chance: 25

#Каждые сколько тиков выростает
grow-cycle: 20

#Список регион
regions:
  - "mine"